apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
# Here noauth overlay is using the same image as alpha
transformers:
- ../../images/alpha
patchesStrategicMerge:
- noauth.yaml
patchesJson6902:
- path: pprof.yaml
  target:
    kind: DaemonSet
    group: apps
    version: v1
    name: csi-gce-pd-node
namespace: gce-pd-csi-driver
images:
- name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  newName: gcr.io/mattcary-e2e/csi/gce-pd-driver
  newTag: pprof-1.17_linux_amd64
